# Configuration for auto-merge bot
version: 2

# Auto-merge rules
pull_requests:
  - match:
      labels:
        - "auto-merge"
        - "dependencies"
      statuses:
        - "success"
      reviews:
        required: false
    merge:
      method: squash
      delete_branch: true

  - match:
      labels:
        - "automated-fix"
        - "approved"
      statuses:
        - "success"
    merge:
      method: squash
      delete_branch: true
      
  - match:
      author: "dependabot[bot]"
      labels:
        - "dependencies"
    merge:
      method: squash
      delete_branch: true
